const categories = [
  'React',
  'TypeScript',
  'Vue',
  'JavaScript',
  '工程化',
  '性能优化',
  '架构',
  'Node.js',
  '数据库',
  '安全',
  '测试',
  '前端趋势',
];

const titlesByCategory: Record<string, string[]> = {
  React: [
    'React Hooks 深入解析',
    'React 18 并发特性实践',
    'React Server Components 初探',
    'React 状态管理方案对比',
    'React 组件设计模式',
    'React 性能优化最佳实践',
    'React 源码阅读笔记',
    'React 自定义 Hook 实战',
    'React 错误边界详解',
    'React 服务端渲染入门',
    'React 19 新特性解读',
    'React 事件系统原理',
    'React Fiber 架构解析',
    'React 渲染流程分析',
    'React 条件渲染技巧',
    'React 列表渲染优化',
    'React Context 性能优化',
    'React 组件懒加载',
    'React 代码分割策略',
    'React 测试框架对比',
    'React Refs 使用详解',
    'React 表单处理最佳实践',
    'React 路由配置指南',
    'React 主题切换实现',
    'React 拖拽功能实现',
  ],
  TypeScript: [
    'TypeScript 高级类型入门',
    'TypeScript 泛型实战',
    'TypeScript 类型体操进阶',
    'TypeScript 类型守卫详解',
    'TypeScript 声明文件编写',
    'TypeScript 模块系统',
    'TypeScript 装饰器使用',
    'TypeScript 枚举与常量',
    'TypeScript 条件类型',
    'TypeScript 模板字面量类型',
    'TypeScript 工具类型速查',
    'TypeScript 类型推断原理',
    'TypeScript 严格模式配置',
    'TypeScript 类型检查性能',
    'TypeScript 与 React 结合',
    'TypeScript 与 Vue 结合',
    'TypeScript 与 Node.js',
    'TypeScript 类型安全实践',
    'TypeScript 类型体操实战',
    'TypeScript 类型系统深度',
    'TypeScript 类型断言详解',
    'TypeScript 接口 vs 类型别名',
    'TypeScript 交叉类型与联合类型',
    'TypeScript 映射类型详解',
    'TypeScript infer 关键字',
  ],
  Vue: [
    'Vue 3 Composition API 详解',
    'Vue 3 响应式原理',
    'Vue 3 组件设计模式',
    'Vue 3 Pinia 状态管理',
    'Vue 3 Vue Router 进阶',
    'Vue 3 性能优化指南',
    'Vue 3 源码阅读笔记',
    'Vue 3 自定义指令实战',
    'Vue 3 组合式函数',
    'Vue 3 服务端渲染',
    'Vue 3 迁移指南',
    'Vue 3 虚拟 DOM 原理',
    'Vue 3 编译优化',
    'Vue 3 事件处理',
    'Vue 3 表单处理',
    'Vue 3 插槽使用',
    'Vue 3 动态组件',
    'Vue 3 异步组件',
    'Vue 3 过渡动画',
    'Vue 3 组合式 API 最佳实践',
    'Vue 3 计算属性详解',
    'Vue 3 侦听器使用',
    'Vue 3 生命周期详解',
    'Vue 3 父子组件通信',
    'Vue 3 依赖注入',
  ],
  JavaScript: [
    'JavaScript 原型链详解',
    'JavaScript 闭包深入理解',
    'JavaScript 作用域与作用域链',
    'JavaScript 事件循环机制',
    'JavaScript 异步编程',
    'JavaScript Promise 详解',
    'JavaScript async/await 实战',
    'JavaScript 数组方法大全',
    'JavaScript 对象操作技巧',
    'JavaScript 模块化发展',
    'JavaScript ES6+ 新特性',
    'JavaScript 设计模式',
    'JavaScript 内存管理',
    'JavaScript 垃圾回收机制',
    'JavaScript 深浅拷贝',
    'JavaScript 类型转换',
    'JavaScript this 指向详解',
    'JavaScript 防抖与节流',
    'JavaScript 柯里化与偏函数',
    'JavaScript 函数式编程入门',
    'JavaScript 正则表达式详解',
    'JavaScript 错误处理最佳实践',
    'JavaScript 模块化规范对比',
    'JavaScript 新特性年度总结',
    'JavaScript 引擎工作原理',
  ],
  工程化: [
    'Vite 构建优化指南',
    'Webpack 配置最佳实践',
    'Rollup 打包原理',
    'ESBuild 性能分析',
    '前端工程化体系搭建',
    'Monorepo 实践指南',
    'Git 工作流规范',
    'CI/CD 自动化部署',
    'Docker 前端容器化',
    'Docker Compose 使用',
    '前端代码规范',
    'ESLint 配置实战',
    'Prettier 格式化',
    'Husky Git Hooks',
    'Commitlint 提交规范',
    '前端依赖管理',
    'package.json 优化',
    'Node 版本管理',
    'pnpm 使用技巧',
    'npm 依赖分析',
    'turbo 构建提速',
    'Changesets 版本管理',
    '语义化版本规范',
    '组件库搭建实战',
    '脚手架工具开发',
  ],
  性能优化: [
    'Core Web Vitals 详解',
    'LCP 优化策略',
    'FID 优化方案',
    'CLS 优化实践',
    '前端性能监控体系',
    '前端性能优化全攻略',
    '图片优化技巧',
    '代码分割策略',
    '懒加载实现',
    '缓存策略优化',
    'HTTP 缓存机制',
    'Service Worker 缓存',
    '前端资源压缩',
    'JS 执行优化',
    '渲染性能优化',
    'DOM 操作优化',
    '长任务优化',
    '首屏加载优化',
    '交互响应优化',
    '性能预算设定',
    'Web Worker 实践',
    '虚拟列表实现',
    '骨架屏优化体验',
    '预加载与预获取',
    'CDN 加速原理',
  ],
  架构: [
    '微前端架构选型',
    'Module Federation 实战',
    'qiankun 微前端',
    'Web Components 应用',
    '前端架构设计原则',
    '组件化开发最佳实践',
    '状态管理方案对比',
    '数据层架构设计',
    'API 设计规范',
    'RESTful API 设计',
    'GraphQL 入门',
    '前后端分离架构',
    'BFF 层设计',
    '网关层设计',
    '边缘计算入门',
    '前端架构演进',
    '技术选型方法论',
    '架构决策记录',
    '系统可观测性',
    '架构安全性设计',
    'DDD 前端实践',
    '插件化架构设计',
    '低代码平台架构',
    '多端适配架构',
    '国际化架构方案',
  ],
  'Node.js': [
    'Node.js 异步编程',
    'Node.js Event Loop 详解',
    'Node.js 内存管理',
    'Node.js 性能监控',
    'Express 框架实战',
    'Koa 框架入门',
    'Fastify 性能对比',
    'Node.js 流处理',
    'Node.js 文件操作',
    'Node.js 网络编程',
    'Node.js 集群模式',
    'Node.js 进程管理',
    'Node.js 错误处理',
    'Node.js 日志系统',
    'Node.js 测试框架',
    'Node.js 数据库操作',
    'Node.js ORM 使用',
    'Node.js Redis 缓存',
    'Node.js WebSocket',
    'Node.js gRPC',
    'Node.js 中间件开发',
    'NestJS 框架入门',
    'Node.js 安全最佳实践',
    'PM2 进程管理',
    'Node.js 部署优化',
  ],
  数据库: [
    'Redis 缓存策略',
    'MySQL 性能优化',
    'PostgreSQL 高级特性',
    'MongoDB 数据建模',
    'SQLite 使用场景',
    '数据库事务详解',
    '数据库索引优化',
    '数据库连接池',
    'ORM 框架对比',
    'Prisma 实战指南',
    'TypeORM 使用',
    'Drizzle ORM 入门',
    '数据库迁移方案',
    '数据库备份恢复',
    '数据库读写分离',
    '数据库分布式锁',
    '数据库一致性',
    '数据库分片',
    '数据库性能监控',
    '数据库安全',
    'Redis 数据结构',
    'Redis 持久化机制',
    'Redis 集群方案',
    'MongoDB 聚合查询',
    '数据库范式详解',
  ],
  安全: [
    'XSS 攻击与防御',
    'CSRF 攻击与防御',
    'SQL 注入防护',
    '前端安全最佳实践',
    'HTTPS 配置',
    'CORS 配置详解',
    'JWT 认证方案',
    'OAuth 2.0 流程',
    '权限设计方案',
    '敏感数据加密',
    '前端防篡改',
    '安全审计日志',
    '依赖安全扫描',
    '安全漏洞修复',
    '安全编码规范',
    '安全测试方法',
    'CSP 策略配置',
    'SRI 子资源完整性',
    '安全响应流程',
    '安全培训要点',
    '点击劫持防御',
    '中间人攻击防护',
    '密码安全存储',
    '会话管理安全',
    '文件上传安全',
  ],
  测试: [
    '单元测试入门',
    '集成测试实战',
    'E2E 测试方案',
    '测试覆盖率分析',
    'Jest 使用技巧',
    'Vitest 性能对比',
    'React Testing Library',
    'Vue Test Utils',
    'Cypress 测试框架',
    'Playwright 测试',
    'Mock 数据管理',
    '测试数据生成',
    '测试环境搭建',
    '测试报告生成',
    '测试自动化',
    '测试 CI 集成',
    '测试策略制定',
    '测试用例设计',
    '测试驱动开发',
    '测试反模式',
    '快照测试实践',
    '接口测试入门',
    '性能测试工具',
    '安全测试入门',
    '测试金字塔模型',
  ],
  '前端趋势': [
    'AI 辅助编程',
    'LLM 前端应用',
    '生成式 UI',
    '无代码平台',
    '边缘计算趋势',
    'WebAssembly 应用',
    'WebGPU 入门',
    'PWA 发展趋势',
    '微前端趋势',
    '组件库发展',
    '设计系统演进',
    '前端工程化趋势',
    '全栈开发趋势',
    '远程开发工具',
    '协作开发趋势',
    '性能优化趋势',
    '安全发展趋势',
    '测试演进趋势',
    '浏览器新特性',
    'Web 标准发展',
    '大前端融合趋势',
    'Serverless 前端',
    'Web3 前端实践',
    '元宇宙前端开发',
    '前端职业发展',
  ],
};

const excerptsByCategory: Record<string, string[]> = {
  React: [
    '深入理解 React Hooks 的工作原理，掌握 useState、useEffect、useContext 等常用 Hook 的最佳实践。',
    '探索 React 18 的并发特性，包括 Concurrent Mode、Suspense、Transition 等新特性的使用场景。',
    '初探 React Server Components，了解服务端组件的优势和适用场景，掌握其在 Next.js 中的应用。',
    '对比 Redux、MobX、Zustand、Jotai 等状态管理方案，选择最适合你的项目的方案。',
    '学习 React 组件设计模式，包括高阶组件、Render Props、组合模式等，提升组件复用性。',
    '掌握 React 性能优化技巧，包括 memo、useMemo、useCallback、虚拟列表等优化手段。',
    '阅读 React 源码，深入理解 React 的核心机制，包括 Diff 算法、协调流程等。',
    '实战编写自定义 Hook，封装可复用的逻辑，提升代码质量和开发效率。',
    '详解 React 错误边界，学会优雅地处理组件渲染错误，提升用户体验。',
    '入门 React 服务端渲染，了解 SSR 和 SSG 的区别，掌握 Next.js 的基本用法。',
  ],
  TypeScript: [
    '深入学习 TypeScript 高级类型，包括交叉类型、联合类型、类型别名、接口等。',
    '掌握 TypeScript 泛型的使用，包括泛型函数、泛型类、泛型约束等高级用法。',
    '挑战 TypeScript 类型体操，通过实战练习提升类型编程能力，解决复杂类型问题。',
    '详解 TypeScript 类型守卫，包括 typeof、instanceof、自定义类型守卫等。',
    '学习编写 TypeScript 声明文件，为第三方库添加类型支持，提升开发体验。',
    '深入理解 TypeScript 模块系统，包括 ES 模块、CommonJS、UMD 等模块格式。',
    '掌握 TypeScript 装饰器的使用，包括类装饰器、方法装饰器、属性装饰器等。',
    '对比 TypeScript 枚举与常量对象，了解它们的适用场景和性能差异。',
    '学习 TypeScript 条件类型，掌握 extends、infer 等关键字的用法。',
    '探索 TypeScript 模板字面量类型，实现类型级别的字符串操作和类型推导。',
  ],
  Vue: [
    '详解 Vue 3 Composition API，包括 setup、ref、reactive、computed、watch 等核心概念。',
    '深入理解 Vue 3 响应式原理，包括 Proxy、依赖收集、触发更新等机制。',
    '学习 Vue 3 组件设计模式，包括组合式函数、指令、插件等，提升组件复用性。',
    '掌握 Vue 3 Pinia 状态管理，了解其与 Vuex 的区别，学会高效管理应用状态。',
    '进阶 Vue 3 Vue Router，包括动态路由、嵌套路由、导航守卫、路由元信息等。',
    '学习 Vue 3 性能优化技巧，包括 memo、shallowRef、虚拟列表、编译优化等。',
    '阅读 Vue 3 源码，深入理解其响应式系统、编译器、运行时等核心模块。',
    '实战编写 Vue 3 自定义指令，封装常用的 DOM 操作和交互逻辑。',
    '学习 Vue 3 组合式函数，封装可复用的逻辑，提升代码质量和开发效率。',
    '入门 Vue 3 服务端渲染，了解 SSR 和 SSG 的区别，掌握 Nuxt.js 的基本用法。',
  ],
  JavaScript: [
    '深入理解 JavaScript 原型链机制，掌握原型继承的原理和实现方式。',
    '全面解析 JavaScript 闭包，了解其形成原理和常见应用场景。',
    '学习 JavaScript 作用域与作用域链，理解变量查找的过程。',
    '掌握 JavaScript 事件循环机制，包括宏任务、微任务的执行顺序。',
    '梳理 JavaScript 异步编程演进历程，从回调到 Promise 再到 async/await。',
    '详解 Promise 的使用，包括 Promise 链、错误处理、并行执行等。',
    '深入理解 async/await，掌握异步代码的同步写法和错误捕获。',
    '系统整理 JavaScript 数组方法，包括遍历、转换、查找、排序等。',
    '掌握 JavaScript 对象操作技巧，包括属性定义、对象合并、深拷贝等。',
    '回顾 JavaScript 模块化发展，从 CommonJS 到 ES Modules 的演进。',
  ],
  工程化: [
    '优化 Vite 构建配置，包括插件配置、路径别名、环境变量、构建优化等。',
    '掌握 Webpack 配置最佳实践，包括入口配置、输出配置、模块规则、插件配置等。',
    '学习 Rollup 打包原理，了解其树摇优化、代码分割、输出格式等特性。',
    '分析 ESBuild 性能优势，了解其基于 Go 语言的实现原理和适用场景。',
    '搭建前端工程化体系，包括构建工具、代码规范、测试框架、CI/CD 等。',
    '实践 Monorepo 管理，使用 pnpm workspace 管理多个项目，提升开发效率。',
    '制定 Git 工作流规范，包括分支管理、代码审查、版本发布等流程。',
    '配置 CI/CD 自动化部署，实现代码提交后自动构建、测试、部署。',
    '容器化前端应用，使用 Docker 打包前端项目，实现环境一致性。',
    '使用 Docker Compose 管理多个容器，包括前端、后端、数据库等服务。',
  ],
  性能优化: [
    '详解 Core Web Vitals，包括 LCP、FID、CLS 的定义、测量方法和优化策略。',
    '优化 LCP（最大内容绘制），包括图片优化、字体优化、资源预加载等。',
    '优化 FID（首次输入延迟），减少 JavaScript 执行时间，提升交互响应速度。',
    '优化 CLS（累积布局偏移），避免页面元素的意外移动，提升用户体验。',
    '搭建前端性能监控体系，包括性能数据采集、存储、分析、告警等。',
    '全面优化前端性能，从加载性能、运行性能、交互性能等多个维度入手。',
    '学习图片优化技巧，包括格式选择、尺寸优化、压缩策略、懒加载等。',
    '掌握代码分割策略，包括路由级分割、组件级分割、动态导入等。',
    '实现懒加载，包括图片懒加载、组件懒加载、路由懒加载等。',
    '优化缓存策略，包括浏览器缓存、Service Worker 缓存、CDN 缓存等。',
  ],
  架构: [
    '选型微前端架构，对比 qiankun、Module Federation、Web Components 等方案。',
    '实战 Module Federation，实现模块共享和远程加载，构建微前端应用。',
    '使用 qiankun 搭建微前端架构，了解其沙箱机制和样式隔离方案。',
    '探索 Web Components，了解自定义元素、Shadow DOM、HTML Templates 等核心概念。',
    '学习前端架构设计原则，包括单一职责、开闭原则、依赖倒置等。',
    '实践组件化开发，掌握组件设计、组件通信、组件复用等最佳实践。',
    '对比各种状态管理方案，包括 Context + useReducer、Zustand、Jotai 等。',
    '设计数据层架构，包括数据获取、状态管理、缓存策略、数据同步等。',
    '制定 API 设计规范，包括 RESTful 设计原则、错误处理、版本管理等。',
    '学习 RESTful API 设计，包括资源命名、HTTP 方法、状态码、参数设计等。',
  ],
  'Node.js': [
    '掌握 Node.js 异步编程，包括回调函数、Promise、async/await 等。',
    '深入理解 Node.js Event Loop，了解其阶段划分和任务执行顺序。',
    '学习 Node.js 内存管理，包括 V8 内存模型、垃圾回收机制、内存泄漏排查。',
    '监控 Node.js 性能，包括 CPU 监控、内存监控、事件循环延迟监控等。',
    '实战 Express 框架，包括路由、中间件、错误处理、模板引擎等。',
    '入门 Koa 框架，了解其洋葱模型、中间件机制、异步处理等特性。',
    '对比 Fastify 与 Express，了解其性能优势和适用场景。',
    '学习 Node.js 流处理，包括可读流、可写流、转换流、管道等。',
    '掌握 Node.js 文件操作，包括文件读写、目录操作、文件系统事件等。',
    '探索 Node.js 网络编程，包括 HTTP、HTTPS、WebSocket、TCP 等。',
  ],
  数据库: [
    '掌握 Redis 缓存策略，包括缓存穿透、缓存击穿、缓存雪崩的解决方案。',
    '优化 MySQL 性能，包括索引优化、查询优化、配置优化、分库分表等。',
    '学习 PostgreSQL 高级特性，包括 JSON 支持、全文搜索、CTE、窗口函数等。',
    '掌握 MongoDB 数据建模，包括文档设计、索引策略、查询优化等。',
    '了解 SQLite 使用场景，包括嵌入式应用、本地存储、测试环境等。',
    '学习数据库事务，包括 ACID 特性、隔离级别、并发控制等。',
    '优化数据库索引，包括主键索引、唯一索引、复合索引、索引失效等。',
    '配置数据库连接池，包括连接池参数、连接管理、性能调优等。',
    '对比 ORM 框架，包括 Prisma、TypeORM、Drizzle ORM 等。',
    '实战 Prisma ORM，包括数据模型定义、CRUD 操作、迁移管理等。',
  ],
  安全: [
    '了解 XSS 攻击原理，掌握预防措施，包括输入过滤、输出转义、CSP 策略等。',
    '学习 CSRF 攻击原理，掌握防御方法，包括 Token 验证、SameSite Cookie 等。',
    '预防 SQL 注入，包括参数化查询、输入验证、ORM 使用等。',
    '制定前端安全最佳实践，包括安全编码规范、依赖安全、数据加密等。',
    '配置 HTTPS，包括 SSL 证书申请、配置、优化等。',
    '详解 CORS 配置，包括跨域请求、预检请求、凭证携带等。',
    '学习 JWT 认证方案，包括 Token 生成、验证、刷新、过期处理等。',
    '了解 OAuth 2.0 流程，包括授权码模式、隐式模式、客户端凭证模式等。',
    '设计权限系统，包括角色权限、资源权限、权限校验等。',
    '加密敏感数据，包括密码哈希、数据加密、传输加密等。',
  ],
  测试: [
    '入门单元测试，学习测试框架、断言库、Mock 工具等。',
    '实战集成测试，测试组件之间的交互和数据流。',
    '学习 E2E 测试方案，包括 Cypress、Playwright、Selenium 等。',
    '分析测试覆盖率，了解语句覆盖率、分支覆盖率、函数覆盖率等。',
    '掌握 Jest 使用技巧，包括测试配置、Mock、快照测试、异步测试等。',
    '对比 Vitest 与 Jest，了解其性能优势和 Vite 集成特性。',
    '学习 React Testing Library，掌握组件测试的最佳实践。',
    '使用 Vue Test Utils 测试 Vue 组件，包括挂载、断言、事件模拟等。',
    '实战 Cypress 测试，包括页面交互、API 测试、自动化测试等。',
    '学习 Playwright 测试，了解其跨浏览器测试能力和自动等待特性。',
  ],
  '前端趋势': [
    '探索 AI 辅助编程工具，包括 Copilot、Cursor、CodeLlama 等。',
    '学习 LLM 前端应用，包括对话系统、内容生成、智能助手等。',
    '了解生成式 UI，探索 AI 驱动的界面生成和布局优化。',
    '分析无代码平台发展，了解其适用场景和技术实现。',
    '探索边缘计算趋势，了解边缘部署、边缘渲染、边缘函数等。',
    '学习 WebAssembly 应用，包括性能优化、跨语言编译、游戏开发等。',
    '入门 WebGPU，了解其图形渲染能力和并行计算潜力。',
    '分析 PWA 发展趋势，包括离线应用、推送通知、安装体验等。',
    '了解微前端趋势，包括架构演进、工具链发展、最佳实践等。',
    '探索组件库发展，包括设计系统、组件生态、主题定制等。',
  ],
};

function generateArticles(): any[] {
  const articles: any[] = [];
  let id = 1;
  
  const startDate = new Date('2023-01-01');
  const endDate = new Date('2026-07-09');
  
  let currentDate = new Date(startDate);
  
  while (currentDate <= endDate) {
    const dayOfWeek = currentDate.getDay();
    if (dayOfWeek === 0) {
      const category = categories[id % categories.length];
      const categoryTitles = titlesByCategory[category];
      const categoryExcerpts = excerptsByCategory[category];
      
      const titleIndex = Math.floor((id - 1) / categories.length) % categoryTitles.length;
      const excerptIndex = Math.floor((id - 1) / categories.length) % categoryExcerpts.length;
      
      const year = currentDate.getFullYear();
      const month = String(currentDate.getMonth() + 1).padStart(2, '0');
      const day = String(currentDate.getDate()).padStart(2, '0');
      
      const readTime = Math.floor(Math.random() * 10) + 6;
      
      articles.push({
        id: String(id),
        title: categoryTitles[titleIndex],
        excerpt: categoryExcerpts[excerptIndex],
        date: `${year}年${parseInt(month)}月${parseInt(day)}日`,
        category,
        readTime: `${readTime} 分钟`,
      });
      
      id++;
    }
    
    currentDate.setDate(currentDate.getDate() + 1);
  }
  
  return articles;
}

const articles = generateArticles();

let output = `export interface Article {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  readTime: string;
}

export const articles: Article[] = [
`;

articles.forEach((article, index) => {
  output += `  {
    id: '${article.id}',
    title: '${article.title}',
    excerpt: '${article.excerpt}',
    date: '${article.date}',
    category: '${article.category}',
    readTime: '${article.readTime}',
  }`;
  if (index < articles.length - 1) output += ',\n';
});

output += `
];
`;

console.log(output);
